"""Read-only source adapters and approval-gated destination adapters."""

from notion_excel_sync.adapters.excel import (
    DuplicateRecordKeyError,
    ExcelReadError,
    ExcelSnapshotReader,
    InvalidHeaderError,
    MissingRecordKeyError,
    MissingWorksheetError,
    SheetSpec,
    SnapshotIdentityMismatch,
    diff_snapshots,
)
from notion_excel_sync.adapters.notion import (
    ApprovalRequiredError,
    HttpNotionGateway,
    InMemoryNotionGateway,
    NotionError,
    NotionGateway,
    NotionMatch,
    NotionPrecondition,
    NotionUpsertResult,
)
from notion_excel_sync.adapters.onedrive import (
    BaselineVersionNotFound,
    DriveEntry,
    DriveFolderDelta,
    DriveItem,
    DriveSearchResult,
    DriveVersion,
    OneDriveError,
    OneDriveReadOnlyClient,
    select_baseline_version,
)
from notion_excel_sync.adapters.telegram import (
    InMemoryTelegramInteraction,
    SentTelegramMessage,
    TelegramAction,
    TelegramButton,
    TelegramCallbackRegistry,
    TelegramCommand,
    TelegramInteraction,
    TelegramMessage,
    TelegramProposalFormatter,
)

__all__ = [
    "ApprovalRequiredError",
    "BaselineVersionNotFound",
    "DriveEntry",
    "DriveFolderDelta",
    "DriveItem",
    "DriveSearchResult",
    "DriveVersion",
    "DuplicateRecordKeyError",
    "ExcelReadError",
    "ExcelSnapshotReader",
    "HttpNotionGateway",
    "InMemoryNotionGateway",
    "InMemoryTelegramInteraction",
    "InvalidHeaderError",
    "MissingRecordKeyError",
    "MissingWorksheetError",
    "NotionError",
    "NotionGateway",
    "NotionMatch",
    "NotionPrecondition",
    "NotionUpsertResult",
    "OneDriveError",
    "OneDriveReadOnlyClient",
    "SentTelegramMessage",
    "SheetSpec",
    "SnapshotIdentityMismatch",
    "TelegramAction",
    "TelegramButton",
    "TelegramCallbackRegistry",
    "TelegramCommand",
    "TelegramInteraction",
    "TelegramMessage",
    "TelegramProposalFormatter",
    "diff_snapshots",
    "select_baseline_version",
]
